name = "vibetech"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[[build]]
command = "pnpm run build:production"
cwd = "./"
watch_dir = "src"

# KV Namespaces (optional - add if needed)
# [[kv_namespaces]]
# binding = "MY_KV"
# id = "your-kv-id"

# Environment variables
[env.production]
name = "vibetech-production"

[env.preview]
name = "vibetech-preview"
