# Comprehensive configuration for prompt-engineer
version: "1.0.0"

analysis:
  max_files_default: 200
  timeout_seconds: 30
  enable_caching: true
  cache_ttl_hours: 24
  incremental_analysis: true
  
  ignore_patterns:
    - node_modules
    - .git
    - dist
    - build
    - __pycache__
    - .pytest_cache
    - venv
    - .venv
    - coverage
    - .coverage
    - .nyc_output
    - target
    - bin
    - obj
    
  file_extensions:
    code:
      - .py
      - .js
      - .jsx
      - .ts
      - .tsx
      - .go
      - .rs
      - .java
      - .cpp
      - .c
      - .h
      - .cs
      - .php
      - .rb
      - .swift
      - .kt
    config:
      - .json
      - .yaml
      - .yml
      - .toml
      - .ini
      - .cfg
      - .conf
    docs:
      - .md
      - .rst
      - .txt
      - .adoc
    styles:
      - .css
      - .scss
      - .sass
      - .less
    markup:
      - .html
      - .xml
      - .svg

security:
  enabled: true
  check_secrets: true
  check_eval: true
  check_xss: true
  check_sql_injection: true
  
  secret_patterns:
    - pattern: 'api[_-]?key'
      severity: critical
      description: "API key detected"
    - pattern: 'password'
      severity: high  
      description: "Password field detected"
    - pattern: 'token'
      severity: high
      description: "Token detected"
    - pattern: 'secret'
      severity: high
      description: "Secret detected"
    - pattern: 'private[_-]?key'
      severity: critical
      description: "Private key detected"
    - pattern: 'access[_-]?key'
      severity: critical
      description: "Access key detected"
      
  severity_weights:
    critical: 15
    high: 3
    medium: 1
    low: 0.5

performance:
  async_enabled: true
  max_workers: null  # Auto-detect CPU count
  chunk_size: 50    # Files per chunk
  memory_limit_mb: 512
  timeout_per_file_ms: 5000
  
  cache:
    enabled: true
    directory: ".prompt_engineer_cache"
    max_size_mb: 100
    compression: true
    
  parallel_processing:
    enabled: true
    thread_pool_size: 4
    process_pool_enabled: false  # Disabled for Windows compatibility
    
quality_metrics:
  enabled: true
  
  complexity:
    max_function_lines: 50
    max_file_lines: 1000
    max_nesting_depth: 4
    
  maintainability:
    min_function_docs: 0.7
    min_class_docs: 0.8
    max_todo_density: 0.05
    
  test_coverage:
    min_coverage_percent: 80
    require_test_files: true
    test_patterns:
      - "*test*.py"
      - "*spec*.js"
      - "*.test.*"
      - "*.spec.*"

ui:
  theme:
    default: "auto"  # auto, light, dark
    primary_color: "#3b82f6"
    success_color: "#10b981" 
    warning_color: "#f59e0b"
    error_color: "#ef4444"
    
  animations:
    enabled: true
    duration_ms: 300
    loading_indicators: true
    
  charts:
    default_type: "interactive"
    color_scheme: "blue"
    show_tooltips: true
    
  export:
    formats:
      - json
      - markdown
      - html
      - csv
    default_format: "json"
    include_charts: true
    
reporting:
  enabled: true
  output_directory: "reports"
  
  formats:
    json:
      enabled: true
      pretty_print: true
      include_metadata: true
    
    markdown:
      enabled: true
      include_toc: true
      include_charts: false
      
    html:
      enabled: true
      template: "default"
      include_css: true
      
  email:
    enabled: false
    smtp_server: ""
    port: 587
    username: ""
    recipients: []
    
integration:
  git:
    enabled: true
    check_commits: true
    analyze_history: true
    blame_analysis: true
    
  ci_cd:
    enabled: false
    providers:
      - github_actions
      - jenkins
      - gitlab_ci
      
  databases:
    enabled: false
    store_history: false
    connection_string: ""
    
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_logging: true
  log_directory: "logs"
  max_file_size_mb: 10
  backup_count: 5
  
  console:
    enabled: true
    colored: true
    
debug:
  enabled: false
  profile_performance: false
  memory_tracking: false
  save_intermediate_results: false
  verbose_errors: false

# Project-specific overrides
project_overrides:
  python:
    analysis:
      max_files_default: 500
    quality_metrics:
      complexity:
        max_function_lines: 40
        
  javascript:
    file_extensions:
      code:
        - .js
        - .jsx
        - .ts
        - .tsx
        - .vue
        
  react:
    quality_metrics:
      maintainability:
        max_component_lines: 200
        require_prop_types: true