directories:
  output: dist-electron
  buildResources: build-resources
  app: .
appId: com.deepcode.editor
productName: DeepCode Editor
asar: false
files:
  - filter:
      - package.json
      - out/**/*
      - dist/**/*
extraResources:
  - from: out
    to: out
    filter:
      - '**/*'
  - from: dist
    to: dist
    filter:
      - '**/*'
win:
  target:
    - nsis
    - portable
  icon: electron/assets/icon.ico
mac:
  target:
    - dmg
    - zip
  icon: electron/assets/icon.icns
  category: public.app-category.developer-tools
linux:
  target:
    - AppImage
    - deb
  icon: electron/assets/icon.png
  category: Development
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 38.4.0
